# Generated by Django 5.1.6 on 2025-04-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_reservation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='category',
            new_name='restaurant',
        ),
    ]
